server:
  port: 8080

# logging:
#   level:
#     root: debug

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,env
#   endpoint:
#     health:
#       show-details: always
#     env:
#       show-details: never

spring:
  datasource:
    url: jdbc:h2:mem:skala-stock
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
